<?php
/**
 * Created by PhpStorm.
 * User: 84333
 * Date: 2019/4/13
 * Time: 19:36
 */

namespace app\common\controller;

use think\Controller;
use think\Config;
use think\Cookie;
use think\Session;

// 引入驗證 Auth類
use app\adminmanage\controller\Auth; 

class Common extends Controller
{
    //页面初始化
    public function _initialize()
    {
        /*
        parent::_initialize(); // TODO: Change the autogenerated stub
        //检测是否登录
         if (!Cookie::get('PHPSESSID')){
            $this -> error('您尚未登入', 'login/namelogin/index', '', 1);
         }else{
            Session_id(Cookie::get('PHPSESSID'));
            if (Session::has('admin_id') && Session::has('admin_name')){
                define('ADMIN_ID', Session::get('admin_id'));
                define('ADMIN_NAME', Session::get('admin_name'));
            }else{
                $this -> error('OOPS！发生错误了！', 'login/namelogin/index', '', 1);
            }
         }*/

        //实例化Common模型类
        $model_common = model('Common');
        //得到所有menu的信息
        $menu_info = $model_common->get_menu_info();
        $this->assign('menu_info',$menu_info);

        //获取当前页面的模块、控制器、方法
        $module = request()->module();
        $controller = request()->controller();
        $action = request()->action();
        //得到当前页面对应的menu_id
        $menu_id = $model_common->get_menu_id($module,$controller,$action);
        $this->assign('menu_id_now',$menu_id);

        //日志记录

        /*
        //权限管理
        $auth = new Auth();
        $rule_name = $controller.'/'.$action; // 規則拼接

        //超級管理員 manage_auth_group id 為 1
        $group = $auth->getGroups(ADMIN_ID);
        if (empty($group)){
            $this -> error('您没有设置任何权限，请联系相关管理员', 'login/namelogin/index', null, 3);
        }
        //獲取組權限
        $group_id = $group[0]['group_id'];
        // 通用頁面
        $general_sites = Config::get('GENERAL');
        // 如果不是超級管理員就必須進行驗證
        if($group_id != 1){
            if (!in_array($rule_name, $general_sites)){
                if(!$auth -> check($rule_name, ADMIN_ID)){
                    $this -> error("您沒有权限",null,-1,1);
                    //$this -> redirect('location:javascript://history.go(-1)');
                }
            }
        }
        */
    }

}