<?php

namespace app\common\controller;

use think\Controller;
use think\Config;
use think\Cookie;
use think\Session;


class Common extends Controller
{
    //页面初始化
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //检测是否登录
         if (!Cookie::get('PHPSESSID')){
            $this -> error('您尚未登入', 'login/namelogin/index', '', 1);
         }else{
            Session_id(Cookie::get('PHPSESSID'));
            if (Session::has('admin_id') && Session::has('admin_name')){
                define('ADMIN_ID', Session::get('admin_id'));
                define('ADMIN_NAME', Session::get('admin_name'));
            }else{
                $this -> error('OOPS！发生错误了！', 'login/namelogin/index', '', 1);
            }
         }

        //实例化Common模型类
        $model_common = model('Common');
        //得到所有menu的信息
        $menu_info = $model_common->get_menu_info();
        $this->assign('menu_info',$menu_info);

        //获取当前页面的模块、控制器、方法
        $module = request()->module();
        $controller = request()->controller();
        $action = request()->action();
        //得到当前页面对应的menu_id
        $menu_id = $model_common->get_menu_id($module,$controller,$action);
        $this->assign('menu_id_now',$menu_id);

        //日志记录

    }

}